version: 0.1.0.{build}
os:
  - Visual Studio 2015
configuration: Release
platform: Any CPU
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore
build:
  publish_wap: true
  verbosity: normal
deploy:
  provider: WebDeploy
  server: https://juniordoctorsstrike.scm.azurewebsites.net:443/msdeploy.axd?site=juniordoctorsstrike
  website: juniordoctorsstrike
  username: $juniordoctorsstrike
  password:
    secure: ZJ+sHOVWyH5y4qnJQBhFDe20KBwJIPFigwpEHXuEse15O0TekPBDCLsHqanEB/qARvAQ4dAiHzRx4eDj69LZOw==
  remove_files: true
  app_offline: true
  skip_dirs: '\\App_Data\\Logs;\\newrelic'
  on:
    branch: master